### ISSUE TITLE
Fix BEM-style CSS in Warehouse

### ISSUE THREAD

**Issue by warpech** [Starcounter/Warehouse#71]
Warehouse contains CSS rules that **almost** follow BEM.

For example, in the file https://github.com/Starcounter/Warehouse/blob/01d2b12e711219fb1edae756d8037308ab55b8de/src/wwwroot/warehouse/css/styles.css there are rules like:

```css
.warehouse {
}

.warehouse__blockquote {
    border-color: darkorange;
    background: white;
}

.warehouse__breadcrumb {
    font-size: 20px;
    margin-bottom: 10px;
}

/* ... */
```

Meaning there is one Block `.warehose` and everything else is an Element in it. 

In my proposal (https://github.com/Starcounter/Starcounter/issues/3450 and http://starcounter.io/guides/web/avoiding-css-conflicts/), this should not be the case:

> It is not correct to use an Element in a HTML template, without the Block declared in the same template. Otherwise you create a implicit coupling of these two templates, which might break when the partial mapping changes.

> If you want to define .chatter-menu in a parent partial and the menu items in a nested partials, these menu items will become new blocks (.chatter-menu-item, not .chatter-menu__item).

Also, BEM.info (https://en.bem.info/method/key-concepts/) defines quite well what is a Block:

> ## Block

> A logically and functionally independent page component, the equivalent of a component in Web Components. A block encapsulates behavior (JavaScript), templates, styles (CSS), and other implementation technologies. Blocks being independent allows for their re-use, as well as facilitating the project development and support process.
